{"time":"2025-05-04T23:58:38.8230103+03:00","level":"INFO","msg":"using version","core version":"0.19.1"}
{"time":"2025-05-04T23:58:38.8230103+03:00","level":"INFO","msg":"created symlink","path":"C:\\Users\\Gilad\\Markman Dropbox\\Gilad Markman\\Python\\Quoridorv15 3\\wandb\\run-20250504_235838-Quoridor84\\logs\\debug-core.log"}
{"time":"2025-05-04T23:58:38.9334488+03:00","level":"INFO","msg":"created new stream","id":"Quoridor84"}
{"time":"2025-05-04T23:58:38.9334488+03:00","level":"INFO","msg":"stream: started","id":"Quoridor84"}
{"time":"2025-05-04T23:58:38.9334488+03:00","level":"INFO","msg":"handler: started","stream_id":"Quoridor84"}
{"time":"2025-05-04T23:58:38.9334488+03:00","level":"INFO","msg":"sender: started","stream_id":"Quoridor84"}
{"time":"2025-05-04T23:58:38.9334488+03:00","level":"INFO","msg":"writer: Do: started","stream_id":"Quoridor84"}
{"time":"2025-05-04T23:58:39.4037693+03:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-05-04T23:58:49.4047828+03:00","level":"ERROR","msg":"monitor: disk: error sampling metrics: Incorrect function."}
{"time":"2025-05-05T02:08:01.0252345+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T02:08:01.0252345+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.100.102.42:51811->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T02:08:24.2287523+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T02:08:24.4160177+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:35:47.7049024+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.100.102.42:52842->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:35:50.3635343+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:36:10.8415453+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:36:13.6875411+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:36:35.9001935+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:36:38.8181663+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:37:05.8736605+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:37:09.7581947+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:37:46.7689779+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:37:50.33909+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:38:43.546086+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T03:38:47.5426419+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:13:38.1148919+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.100.102.42:50814->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:13:39.3845286+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:14:01.3326323+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:14:02.5864792+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:14:26.5598601+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:14:28.4017495+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:14:56.3587073+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:14:57.9963358+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:47:22.7725104+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:47:24.1902163+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.100.102.42:51217->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:47:45.9611571+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:47:47.4640964+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T04:47:50.2340028+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-05T04:47:51.5691649+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-05T04:47:59.798084+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-05T04:48:01.4865205+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-05T07:05:25.1379862+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T07:05:27.0776071+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.100.102.42:52672->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T07:05:48.5090978+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T07:05:50.4676269+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T07:06:14.0685023+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/giladmarkman/Quoridor/Quoridor84/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-05T07:06:15.8212915+03:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
